[package]
name = "ipttrace"
version = "0.1.0"
authors = ["Sirui Mu <msrlancern@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
colored = "2.0.0"
libipttrace = { path = "../libipttrace" }
